name: Update Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get version number
        id: get_version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION)
          else
            VERSION="1.0.0"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get recent commit message
        id: get_commit
        run: |
          RECENT_COMMIT=$(git log -1 --pretty=%B | head -n 1)
          echo "RECENT_COMMIT=$RECENT_COMMIT" >> $GITHUB_ENV

      - name: Generate version.json
        run: |
          echo "Generating version.json"
          cat <<EOF > docs/json/version.json
          {
              "number": "${{ env.VERSION }}",
              "time-updated": "$(date)",
              "recent-commit": "${{ env.RECENT_COMMIT }}"
          }
          EOF
          echo "version.json generated successfully"

      - name: Commit and push changes
        run: |
          git add docs/json/version.json
          git commit -m "(Chore): Update Version"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}